### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by aniqueta** [zero88/gh-release-downloader#3]
@zero88 Thanks for making this. With the addition of LC_CTYPE=C before the tr command on line 93, this script can become macOS compatible too. I think it would maintain Linux functionality, but not sure. Didn't think this needed a full pull request. Just offering a suggestion.

**Comment by zero88** [comment]
Thank @aniqueta 
I already fixed it, test with Linux is fine. but cannot test on macOS due to I don't have it :laughing: 
Could you pls help me to verify it by downloading artifact then remove suffix `.zip`
[ghrd.zip](https://github.com/zero88/gh-release-downloader/files/6073247/ghrd.zip)

After your confirmation, I will go to release it

**Comment by aniqueta** [comment]
Thanks @zero88 I had already made that change to make it work on macOS, and I've had no issues. I tested your version, which looks identical, and also no issues. :)

**Comment by aniqueta** [comment]
I would also suggest adding the following installation instructions for macOS, with a requirement for Homebrew (which already maps /usr/local/bin to PATH). 

sudo curl -L https://github.com/zero88/gh-release-downloader/releases/download/v1.1.1/ghrd -o /usr/local/bin/ghrd \
   && sudo chmod +x /usr/local/bin/ghrd \
   && brew install jq

**Comment by zero88** [comment]
Cool, thank you.
New version is released
